application/address/urls.py
from django.urls import path
from . import views

app_name='address'

urlpatterns = [
    path('', views.insert, name='insert'),
    path('register', views.register, name='register'),
]

application/application/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('address/', include('address.urls')),
]

application/users/urls.py
from django.urls import path
from . import views

app_name='users'

urlpatterns = [
    path('', views.search, name='search'),
    path('answer', views.searchResult, name='searchResult'),
]

application/address/models.py
from django.db import models

# Create your models here.

application/users/models.py
from django.db import models

# Create your models here.


class User(models.Model):
    first_name = models.CharField(max_length=250, unique=True)
    last_name = models.CharField(max_length=250, unique=True)
    phone = models.IntegerField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '{}'.format(self.name)


class UserAddress(models.Model):
    subject = models.CharField(max_length=250, unique=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    number_of_address = models.IntegerField()
    coordination = models.IntegerField()
    is_user = models.BooleanField(default=True)
    is_supporter = models.BooleanField(default=False)

    def __str__(self):
        return '{}'.format(self.subject)

application/address/views.py
from django.shortcuts import render
from users.models import User, UserAddress

# Create your views here.

def insert(request):
    return render(request, 'address/data.html')

def register(request):
    if request.method=="POST":
        q = request.POST['id']
        s = request.POST['subject']
        c = request.POST['coordination']
        user = User.objects.get(id=q)
        u = UserAddress(subject=s,user=user,coordination=c)
        u.save()
        send_notification()

def send_notification(request):
    print("One new address is created")

application/users/views.py
from django.shortcuts import render
from .models import User, UserAddress

# Create your views here.

def search(request):
    return render(request, 'users/search.html')

def searchResult(request):
    user = None
    query1 = None
    query = None
    address1 = None
    if 'q' and 'p' in request.GET:
        query = request.GET.get('q')
        query1 = request.GET.get('p')
        user = User.objects.get(first_name=query, last_name__contains=query1)
        if 'o' in request.GET:
            query = request.GET.get('o')
            address1 = UserAddress.objects.get(user=user)
            if int(address1.number_of_address) > int(query):
                return render(request, 'users/result.html',{'user':user, 'address1':address1})
        if 'i' in request.GET:
            query = request.GET.get('i')
            address1 = UserAddress.objects.get(user=user)
            if int(address1.number_of_address) < int(query):
                return render(request, 'users/result.html',{'user':user, 'address1':address1})
        if 'u' in request.GET:
            query = request.GET.get('u')
            address1 = UserAddress.objects.get(user=user)
            if int(address1.number_of_address) == int(query):
                return render(request, 'users/result.html',{'user':user, 'address1':address1})

application/address/templates/address/data.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <body>
        <form action="{% url 'address:register' %}" method="post">
            {% csrf_token %}
            <input type="text" placeholder="id" name="id">
            <input type="text" placeholder="subject" name="subject">
            <input type="text" placeholder="coordination" name="coordination">
            <button type="submit">جستجو</button>
        </form>        
    </body>
</html>

application/users/templates/users/result.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <body>
       <p>user's name is: {{user.first_name}}</p>
       <p>user's last name is: {{user.last_name}}</p>
       <p>number of addresses is: {{user.first_name}}</p>
    </body>
</html>

application/users/templates/users/search.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <body>
        <form action="{% url 'users:searchResult' %}" method="get">
            {% csrf_token %}
            <input type="search" placeholder="جستجوی نام" name="q">
            <input type="search" placeholder="جستجوی خانوادگی" name="p">
            <input type="search" placeholder="بیشتر از این تعداد آدرس" name="o">
            <input type="search" placeholder="کمتر از این تعداد آدرس" name="i">
            <input type="search" placeholder="مساوی این تعداد آدرس" name="u">
            <button type="submit">جستجو</button>
        </form>        
    </body>
</html>